### ISSUE TITLE
Allow the `showencryption` Option for Checks

### ISSUE THREAD

**Issue by Ataraxic** [sekipaolo/pypingdom#59]
I'm using this library as part of an ansible script, and I wanted to support encryption as a property that we can edit. In order for me to do this I need to pass the param `"show_encryption": True` [here](https://github.com/sekipaolo/pypingdom/blob/master/pypingdom/client.py#L31). This also requires that the property `verify_certificate` be added [here](https://github.com/sekipaolo/pypingdom/blob/master/pypingdom/check.py#L8). 

Are you open to a PR where Client can take params and the corresponding `SKIP_ON_JSON` change?

**Comment by Ataraxic** [comment]
The setting is actually `showencryption` without an underscore and does seem to be documented here 
![image](https://user-images.githubusercontent.com/9220647/42708315-f293ae5a-86aa-11e8-8968-b479e5d42b4c.png). 

The update method does accept this here: 
![image](https://user-images.githubusercontent.com/9220647/42708407-35f9b590-86ab-11e8-9cf5-09dc2b48b89c.png)

I will try to run the tests to verify they pass.

**Comment by infothrill** [comment]
@Ataraxic this should now be fixed through pull request #78
